Use `watchfiles` as a file watching backend
getpelican/pelican pull request #3151
Opened 2023-06-21 21:00 UTC by RealOrangeOne

This doesn't use polling unless absolutely necessarily, making it more efficient. It also reduces the amount of first-party code required, and simplifies working out which files are being watched.

# Pull Request Checklist

- [ ] Ensured **tests pass** and (if applicable) updated functional test output
- [ ] Conformed to **code style guidelines** by running appropriate linting tools
- [ ] Added **tests** for changed code
- [ ] Updated **documentation** for changed code

2023-06-22 14:53 UTC, avaris commented
I'll review when I get the time but before that you also need to add it to the requirements list in `setup.py`.

2023-08-14 21:35 UTC, avaris requested changes
Also, linter wants some changes.

2023-08-14 21:35 UTC, avaris commented on pelican/utils.py
> +    watching_paths = [os.path.abspath(p) for p in watching_paths if p and os.path.exists(p)]
Might still be a good idea to warn if watched path does not exist.

2023-10-28 15:31 UTC, avaris approved these changes
Had to make some changes. 
* For not-existing paths it was erroring out, so had to take them out of watch list
* Changed the order of `pelican.run()`, otherwise it was waiting awkwardly for a change before it run at the start.

2023-10-28 21:23 UTC, justinmayer approved these changes
Many thanks to @RealOrangeOne and @avaris for this enhancement! ✨

2023-10-28 21:23 UTC, merged