Fix #3233 -- Simple theme classless semantic HTML
getpelican/pelican pull request #3234
Opened 2023-10-30 17:29 UTC by pauloxnet

# Pull Request Checklist

Resolves: #3233

- [ ] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [ ] Added **tests** for changed code
- [x] Updated **documentation** for changed code

2023-10-30 17:51 UTC, pauloxnet commented
I'll wait to receive a fe feedback before completing this PR with updated tests

2023-11-10 21:57 UTC, avaris requested changes
Left some minor suggestions to docs. Overall looks good to me. Obviously, needs updates to the tests.

2023-11-10 21:57 UTC, avaris commented on docs/settings.rst
> +The built-in ``simple`` can be customized using the following settings.
"The built-in ``simple`` **theme** can be ..."

2023-11-10 21:57 UTC, avaris commented on docs/settings.rst
> +   The URL of a theme to use as a style sheet.
"The URL of the stylesheet to use"

I understand the intent behind the "theme" here but I think it could be confused with `pelican` theme

2023-11-11 10:15 UTC, pauloxnet commented
> Left some minor suggestions to docs.

Thanks, I've applied both of your suggestions to my code.

> Overall looks good to me. Obviously, needs updates to the test output.

I was waiting for some feedback before fixing tests, thank to your review I'll do it.

2023-11-11 10:20 UTC, justinmayer commented
@pauloxnet: Wonderful. We are getting close to releasing Pelican 4.9 and would like to include this PR, so thank you for being so responsive! 🌟

2023-11-11 10:25 UTC, pauloxnet commented
> @pauloxnet: Wonderful. We are getting close to releasing Pelican 4.9 and would like to include this PR, so thank you for being so responsive! 🌟

I would also like to see this improved version of the "simple" theme in Pelican 4.9. ✨ 

I'll try to find time to work on it this weekend. 🤞🏻

2023-11-11 13:16 UTC, pauloxnet commented
@avaris tests are fixed, there's still a requested change from you I think. ;-)

@justinmayer I think the PR is ready to be merged :-)

2023-11-11 22:13 UTC, avaris approved these changes
Thanks!

2023-11-12 06:57 UTC, justinmayer approved these changes
Many thanks to @pauloxnet for the enhancement and to @avaris for reviewing. 👍

2023-11-12 06:58 UTC, merged

2024-01-29 04:44 UTC, vapier commented on pelican/themes/simple/templates/pagination.html
> +        <li><a href="{{ SITEURL }}/{{ last_page.url }}">&Rang;</a></li>
was it really intentional to move these into dedicated bullet points ?  prior to 4.9, these would be on one-line, but now it's split out.

## prior-to 4.9

```
Page 1 / 2 » ⇉
```

## after this commit

```
* Page 1 / 2
* ⟩
* ⟫
```